spring:
  config:
    activate:
      on-profile: "prod"

cards:
  message: "Welcome to Cards Microservice related production environment"
  description: "This microservice is responsible for managing user cards."
  contact:
    name: "Saulo Santos"
    email: "santos@example.com"
  onCallSupport:
    - (+55) 11 99999-9999
    - (+55) 11 88888-8888

