services:
  accounts:
    image: "saulolv/accounts:v1"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
        - app-network

  loans:
    image: "saulolv/loans:v1"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
        - app-network

  cards:
    image: "saulolv/cards:v1"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
        - app-network

networks:
  app-network:
    driver: bridge