spring:
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  datasource:
    url: jdbc:h2:mem:loansdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8090

build:
  version: "1.3.0"

loans:
  message: "Welcome to Loans Microservice"
  description: "This microservice is responsible for managing user loans."
  contact:
    name: "Saulo Santos"
    email: "example@example.com"
