spring:
  application:
      name: accounts
  profiles:
      active: qa
  # MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
    port: 8080