services:
  rabbitmq:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "saulolv/configserver:v1.2"
    container_name: "configserver-ms"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    extends:
      service: microservice-base-config
      file: common-config.yml

  accounts:
    image: "saulolv/accounts:v1.2"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      service: microservice-configserver-config
      file: common-config.yml

  loans:
    image: "saulolv/loans:v1.2"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      service: microservice-configserver-config
      file: common-config.yml

  cards:
    image: "saulolv/cards:v1.2"
    container_name: "cards-ms"
    ports:
      - "9010:9000"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      service: microservice-configserver-config
      file: common-config.yml

networks:
  app-network:
    driver: bridge