spring:
  application:
    name: config-server
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/saulolv/config-bank-microservices.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"      #search-locations: classpath:/config/

management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: "12345678901234567890123456789012"




server:
  port: 8071