spring:
  application:
    name: config-server
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/saulolv/config-bank-microservices.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
          #search-locations: classpath:/config/


server:
  port: 8071